const data = {
  labels: Array.apply(null, {length:30}).map(Number.call, Number),
  datasets: [
    {
      label: "Worker Score",
      fill: true,
      lineTension: 0.1,
      backgroundColor: "rgba(72,166,242,1)",
      borderColor: "rgba(72,166,242,1)",
      borderCapStyle: "butt",
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: "miter",
      pointBorderColor: "rgba(72,166,242,1)",
      pointBackgroundColor: "#fff",
      pointBorderWidth: 1,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: "rgba(72,166,242,1)",
      pointHoverBorderColor: "rgba(72,166,242,1)",
      pointHoverBorderWidth: 2,
      pointRadius: 1,
      pointHitRadius: 10,
      data: Array.apply(null, {length:30}).map(Function.call, ()=>{return Math.random() + 4;})
    },
    {
      label: "Supplier Score",
      fill: true,
      lineTension: 0.1,
      backgroundColor: "orange",
      borderColor: "orange",
      borderCapStyle: "butt",
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: "miter",
      pointBorderColor: "orange",
      pointBackgroundColor: "#fff",
      pointBorderWidth: 1,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: "orange",
      pointHoverBorderColor: "orange",
      pointHoverBorderWidth: 2,
      pointRadius: 1,
      pointHitRadius: 10,
      data: Array.apply(null, {length:30}).map(Function.call, ()=>{return Math.random() + 2;})
    },
    {
      label: "Agent Score",
      fill: true,
      lineTension: 0.1,
      backgroundColor: "purple",
      borderColor: "purple",
      borderCapStyle: "butt",
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: "miter",
      pointBorderColor: "purple",
      pointBackgroundColor: "#fff",
      pointBorderWidth: 1,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: "purple",
      pointHoverBorderColor: "purple",
      pointHoverBorderWidth: 2,
      pointRadius: 1,
      pointHitRadius: 10,
      data: Array.apply(null, {length:30}).map(Function.call, ()=>{return Math.random() + 3})
    },
    {
      label: "Investment Score",
      fill: true,
      lineTension: 0.1,
      backgroundColor: "darkgreen",
      borderColor: "darkgreen",
      borderCapStyle: "butt",
      borderDash: [],
      borderDashOffset: 0.0,
      borderJoinStyle: "miter",
      pointBorderColor: "darkgreen",
      pointBackgroundColor: "#fff",
      pointBorderWidth: 1,
      pointHoverRadius: 5,
      pointHoverBackgroundColor: "darkgreen",
      pointHoverBorderColor: "darkgreen",
      pointHoverBorderWidth: 2,
      pointRadius: 1,
      pointHitRadius: 10,
      data: Array.apply(null, {length:30}).map(Function.call, ()=>{return Math.random() + 2})
    }
  ]
};

export { data };
